on:
  workflow_dispatch

env:
  # Enable reproducibility-related build system workarounds
  REPRODUCIBLE_BUILD: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
        with:
          repository: 'fxarb/openeuicc'
          submodules: recursive

      - name: Decode Keystore
        uses: timheuer/base64-to-file@v1.2.4
        with:
          fileName: openeuicc.keystore
          fileDir: ${{ env.GITHUB_WORKSPACE }}
          encodedString: ${{ secrets.SIGNINGKEYBASE64 }}
          
      - name: Decode Secret Signing Configuration
        uses: timheuer/base64-to-file@v1.2.4
        with:
          fileName: keystore.properties
          fileDir: ${{ env.GITHUB_WORKSPACE }}
          encodedString: ${{ secrets.OPENEUICC_SIGNING_CONFIG }}

      - name: Add Keystore Path to Config
        run:  |
          sudo echo "storeFile=${{ env.GITHUB_WORKSPACE }}/openeuicc.keystore" >> ${{ env.GITHUB_WORKSPACE }}/keystore.properties


      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Release APK ( OpenEUICC only)
        run: ./gradlew --no-daemon :app:assembleRelease

      - name: Upload APK files
        uses: actions/upload-artifact@v4
        with:
          name: OpenEUICC.apk
          path: app/build/outputs/apk/release/*.apk
